# Import in libraries for path, data, and plotting handling
import os
import numpy
from pathlib import Path
import matplotlib.pyplot as plt

# Import allensdk classes/functions
from allensdk.model.biophys_sim.config import Config
from allensdk.model.biophysical.utils import Utils
from allensdk.core.dat_utilities import DatUtilities

import tracemalloc

tracemalloc.start()

# Change the working directory to where the perisomatic model is
parent_path = Path(__file__).resolve().parent.parent
os.chdir(parent_path / "neuron_models" / "perisomatic")

# Load in the description and utils
description = Config().load("manifest.json")
utils = Utils(description)
h = utils.h

# Load in the morphology and cell parameters generated by NEURON
manifest = description.manifest
morphology_path = manifest.get_path("MORPHOLOGY")
utils.generate_morphology(morphology_path.encode("ascii", "ignore"))
utils.load_cell_parameters()

# Generate a stimulus of 0.48 nA
stim = h.IClamp(h.soma[0](0.5))
stim.amp = 0.48
stim.delay = 1000.0
stim.dur = 1000.0

# Define how long the stimulus will last
h.tstop = 3000.0

vec = utils.record_values()

# Run the model
h.finitialize()
h.run()

# Output and plot the data created
output_path = "output_voltage.dat"

junction_potential = description.data["fitting"][0]["junction_potential"]
mV = 1.0e-3
ms = 1.0e-3

output_data = (numpy.array(vec["v"]) - junction_potential) * mV
output_times = numpy.array(vec["t"]) * ms

plt.plot(output_times, output_data)
plt.show()

DatUtilities.save_voltage(output_path, output_data, output_times)

# Get memory usage
current, peak = tracemalloc.get_traced_memory()

print(f"Current: {current / (1024 * 1024):.2f} MB")
print(f"Peak: {peak / (1024 * 1024):.2f} MB")

tracemalloc.stop()
